name = "DHH"
author = "Vsevolod Dobrovolskyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69689f662bf2cddfd877fe6ebb38a411e4dccc4be16f475ddc2a614b7bfdbf3b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"

[options]
acceptable-game-versions = "1.21.1"
