name = "DHH"
author = "Vsevolod Dobrovolskyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "923bea6719e4048d8673314ba8f738e0fbe08ec3a626b30c7b11ef5867ac4903"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.5", "1.21.8", "1.21.9", "1.21.10"]
