name = "DHH"
author = "Vsevolod Dobrovolskyi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d3690fbe507ffe16bd89614866914b0a87ded3e2a3f5e60f6c300a9c5464bf3"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.34-beta"

[options]
acceptable-game-versions = ["1.21.10", "1.21.11", "1.21.1", "1.21"]
